# Generated by Django 6.0.5 on 2026-05-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produtos',
            options={'ordering': ['-produto'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
